### ISSUE TITLE
Is XrmRichTextEditor compatible with 7.1 turbo forms?

### ISSUE THREAD

**Issue by khadimali** [BackToTheCrm/XrmRichTextEditor#1]
Hello Clement,

I am receiving '$ is not defined' script error. It appears the package is still not compatible with 7.1 turbo forms? Or am i missing something?

**Comment by AdCodicem** [comment]
Hi Ali,
It appears I forgotten to add jQuery to the solution.
I added it, you can download the new release [here](https://github.com/BackToTheCrm/XrmRichTextEditor/releases/tag/v1.0.1.0).
